# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchCDFWindow.ui',
# licensing of 'searchCDFWindow.ui' applies.
#
# Created: Fri Mar  6 12:32:35 2020
#      by: pyside2-uic  running on PySide2 5.13.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(370, 470)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.listPathCDFWidget = QtWidgets.QListWidget(Dialog)
        self.listPathCDFWidget.setMinimumSize(QtCore.QSize(300, 300))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.listPathCDFWidget.setFont(font)
        self.listPathCDFWidget.setObjectName("listPathCDFWidget")
        self.gridLayout.addWidget(self.listPathCDFWidget, 1, 0, 1, 2)
        self.buttonMultipleCDF = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonMultipleCDF.sizePolicy().hasHeightForWidth())
        self.buttonMultipleCDF.setSizePolicy(sizePolicy)
        self.buttonMultipleCDF.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonMultipleCDF.setFont(font)
        self.buttonMultipleCDF.setObjectName("buttonMultipleCDF")
        self.gridLayout.addWidget(self.buttonMultipleCDF, 2, 0, 2, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setFlat(True)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkSameSampleYes = QtWidgets.QRadioButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkSameSampleYes.sizePolicy().hasHeightForWidth())
        self.checkSameSampleYes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkSameSampleYes.setFont(font)
        self.checkSameSampleYes.setChecked(True)
        self.checkSameSampleYes.setObjectName("checkSameSampleYes")
        self.verticalLayout_6.addWidget(self.checkSameSampleYes)
        self.checkSameSampleNo = QtWidgets.QRadioButton(self.groupBox_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkSameSampleNo.sizePolicy().hasHeightForWidth())
        self.checkSameSampleNo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkSameSampleNo.setFont(font)
        self.checkSameSampleNo.setObjectName("checkSameSampleNo")
        self.verticalLayout_6.addWidget(self.checkSameSampleNo)
        self.gridLayout.addWidget(self.groupBox_10, 2, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        self.groupBox_11.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.checkReadUnitsYes = QtWidgets.QRadioButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkReadUnitsYes.sizePolicy().hasHeightForWidth())
        self.checkReadUnitsYes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkReadUnitsYes.setFont(font)
        self.checkReadUnitsYes.setChecked(True)
        self.checkReadUnitsYes.setObjectName("checkReadUnitsYes")
        self.verticalLayout_7.addWidget(self.checkReadUnitsYes)
        self.checkReadUnitsNo = QtWidgets.QRadioButton(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkReadUnitsNo.sizePolicy().hasHeightForWidth())
        self.checkReadUnitsNo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.checkReadUnitsNo.setFont(font)
        self.checkReadUnitsNo.setObjectName("checkReadUnitsNo")
        self.verticalLayout_7.addWidget(self.checkReadUnitsNo)
        self.gridLayout.addWidget(self.groupBox_11, 3, 1, 2, 1)
        self.buttonOneCDF = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonOneCDF.sizePolicy().hasHeightForWidth())
        self.buttonOneCDF.setSizePolicy(sizePolicy)
        self.buttonOneCDF.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonOneCDF.setFont(font)
        self.buttonOneCDF.setObjectName("buttonOneCDF")
        self.gridLayout.addWidget(self.buttonOneCDF, 4, 0, 1, 1)
        self.buttonDeletePath = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonDeletePath.setFont(font)
        self.buttonDeletePath.setObjectName("buttonDeletePath")
        self.gridLayout.addWidget(self.buttonDeletePath, 5, 0, 1, 1)
        self.buttonAccept = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.buttonAccept.setFont(font)
        self.buttonAccept.setObjectName("buttonAccept")
        self.gridLayout.addWidget(self.buttonAccept, 5, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "CDF window", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "CDF PATH FILES", None, -1))
        self.buttonMultipleCDF.setText(QtWidgets.QApplication.translate("Dialog", "Find with TXT", None, -1))
        self.groupBox_10.setTitle(QtWidgets.QApplication.translate("Dialog", "Maximum sample rate to all sensors?", None, -1))
        self.checkSameSampleYes.setText(QtWidgets.QApplication.translate("Dialog", "Yes", None, -1))
        self.checkSameSampleNo.setText(QtWidgets.QApplication.translate("Dialog", "No", None, -1))
        self.groupBox_11.setTitle(QtWidgets.QApplication.translate("Dialog", "Read units and full name?", None, -1))
        self.checkReadUnitsYes.setText(QtWidgets.QApplication.translate("Dialog", "Yes", None, -1))
        self.checkReadUnitsNo.setText(QtWidgets.QApplication.translate("Dialog", "No", None, -1))
        self.buttonOneCDF.setText(QtWidgets.QApplication.translate("Dialog", "Find without TXT", None, -1))
        self.buttonDeletePath.setText(QtWidgets.QApplication.translate("Dialog", "Delete selected items", None, -1))
        self.buttonAccept.setText(QtWidgets.QApplication.translate("Dialog", "Accept", None, -1))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

